export const images = {
  logo: require('./techtiz-logo.png'),
  designIcon: require('./design.png'),
  ideationIcon: require('./ideation.png'),
  softwareDevIcon: require('./software-dev.png'),
  supportIcon: require('./support.png'),
  teamArgumentIcon: require('./term-argument.png'),
  fixedPriceIcon: require('./fixed_Price.png'),
  dedicatedResourceIcon: require('./dedicated_resource.png'),
  iosIcon: require('./ios.png'),
  androidIcon: require('./android.png'),
  flutterIcon: require('./flutter.png'),
  quotes: require('./quotes.png'),
  person: require('./person.png'),
  clutch: require('./clutch.png'),
  enterprise: require('./epr.jpg'),
  smallC: require('./small-c.png'),
  startup: require('./startup.png'),
  listBullet: require('./list-bullet.png'),
}
